apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: dev-prometheus
spec:
  storageClassName: standard
  volumeName: grafana-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi