apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: dev-prometheus
spec:
  storageClassName: standard
  volumeName: prometheus-pv-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi