apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-1
  namespace: dev-prometheus
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
