apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-0
spec:
  storageClassName: normal
  volumeName: redis-pv-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-1
spec:
  storageClassName: normal
  volumeName: redis-pv-02
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-2
spec:
  storageClassName: normal
  volumeName: redis-pv-03
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-3
spec:
  storageClassName: normal
  volumeName: redis-pv-04
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-4
spec:
  storageClassName: normal
  volumeName: redis-pv-05
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-cluster-5
spec:
  storageClassName: normal
  volumeName: redis-pv-06
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi