apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: default
spec:
  ports:
  - name: nginx-port
    port: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort