apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  namespace: default
spec:
  ports:
  - name: redis-master-port
    port: 80
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort