#Install VPA at first
#git clone https://github.com/kubernetes/autoscaler.git
#cd autoscaler/vertical-pod-autoscaler
#./hack/vpa-up.sh

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx # or just image: nginx
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 5m
              memory: 5Mi
          ports:
            - containerPort: 80