apiVersion: v1
kind: Service
metadata:
  name: httpd-service-xfusion
  namespace: httpd-namespace-xfusion
spec:
  type: NodePort
  selector:
    app: httpd_app_xfusion
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004