apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - name: my-volume
          mountPath: /app
      volumes:
      - name: my-volume
        configMap:
          name: my-configmap